config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'viz_ones#index'

    resources :viz_ones, only: [:index] do
      collection do
        post :search
      end
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/viz_one.rb
class VizOne < ApplicationRecord

  def self.search(params)

    puts params

    sql_select = 
        "SELECT 
            TB1.PATIENT_ID AS id_value
            , '#{params[:x_measure]}' AS x_name
            , TB1.#{params[:x_measure]} as x_value
            , '#{params[:y_measure]}' AS y_name
            , TB1.#{params[:y_measure]} as y_value"

    sql_select_grouping = if params[:grouping] == "none"
                            "'#{params[:grouping]}' AS grouping_value"
                          else
                            "REPLACE(TB1.#{params[:grouping]}, ' ', '_') AS grouping_value" 
                          end  

    sql_from = 
        "FROM VIZ_ONES TB1"

    sql_where = 
        "WHERE 
        TB1.ETHNICITY IN ('#{params[:ethnicity].join("','")}')
        AND TB1.SEX IN ('#{params[:sex].join("','")}')
        AND TB1.YEAR = #{params[:year]}
        AND TB1.DIABETES_TYPE IN ('#{params[:diabetes_type].join("','")}')  
        AND TB1.#{params[:x_measure]} IS NOT NULL
        AND TB1.#{params[:y_measure]} IS NOT NULL"
  
    sql_complete = sql_select + ", " + sql_select_grouping + " " + sql_from + " " + sql_where
        
    results = self.find_by_sql(sql_complete)


  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

end

app/controllers/viz_ones_controller.rb
class VizOnesController < ApplicationController

	def index
	end

  def search
    @viz_ones = VizOne.search(params)

    # This is going to render the partial, which will behanlded by viz_one.js
    respond_to do |format|
      format.html
      format.json { render json: @viz_ones }
    end

  end

  private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Welcome to the KHP-D Interactive Platform</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KHPDIp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/viz_ones/_controls.html.erb
<div class="side-bar-item controls">
  <div class="control-year">
	<input type="text" value=2009 name="year" id="year" class="year-box" value="year">
  </div>
	<div class="control-list">
		<button type="button" class="btn control-left"><i class="far fa-arrow-alt-circle-left fa-2x"></i></button>
		<button type="button" class="btn"><i class="far fa-play-circle fa-2x control-center"></i></button>
		<button type="button" class="btn control-right"><i class="far fa-arrow-alt-circle-right fa-2x"></i></button>
	</div>
</div>

app/views/viz_ones/_diabetes_type.html.erb
  <h3>Diabetes Type</h3>
    <div class="filter-list-3">
    <label class="checkbox-container">Type 1
      <%= check_box_tag('diabetes_type[]', "T1", true, {:multiple => true, :class => 'input_checkbox'}) %>
      <span class="checkbox-checkmark"></span>
    </label>

    <label class="checkbox-container">Type 2
      <%= check_box_tag('diabetes_type[]', "T2", true, {:multiple => true, :class => 'input_checkbox'}) %>
      <span class="checkbox-checkmark"></span>
    </label>

    <label class="checkbox-container">GDM
      <%= check_box_tag('diabetes_type[]', "GDM", true, {:multiple => true, :class => 'input_checkbox'}) %>
      <span class="checkbox-checkmark"></span>
    </label>

    <label class="checkbox-container">Other
      <%= check_box_tag('diabetes_type[]', "OTHER", true, {:multiple => true, :class => 'input_checkbox'}) %>
      <span class="checkbox-checkmark"></span>
    </label>
  </div>

app/views/viz_ones/_ethnicity.html.erb
<h3>Ethnicity</h3>
<div class="filter-list-1">
  <label class="checkbox-container">White
    <%= check_box_tag('ethnicity[]', "WHITE", true, class:'input_radio') %>
    <span class="checkbox-checkmark"></span>
  </label>

  <label class="checkbox-container">Asian or Asian British
    <%= check_box_tag('ethnicity[]', "ASIAN OR ASIAN BRITISH", true, class:'input_radio') %>
    <span class="checkbox-checkmark"></span>
  </label>

  <label class="checkbox-container">Black or Black British
    <%= check_box_tag('ethnicity[]', "BLACK OR BLACK BRITISH", true, class:'input_radio') %>
    <span class="checkbox-checkmark"></span>
  </label>

  <label class="checkbox-container">Mixed
    <%= check_box_tag('ethnicity[]', "MIXED", true, class:'input_radio') %>
    <span class="checkbox-checkmark"></span>
  </label>

  <label class="checkbox-container">Other Ethnic Groups
    <%= check_box_tag('ethnicity[]', "OTHER ETHNIC GROUPS", true, class:'input_radio') %>
    <span class="checkbox-checkmark"></span>
  </label>
</div>

app/views/viz_ones/_filter.html.erb
<div class="side-bar-item filters">
  <h2>Filters</h2>
    <%= render('viz_ones/ethnicity') %>
    <%= render('viz_ones/sex') %>
    <%= render('viz_ones/diabetes_type') %>
</div>

app/views/viz_ones/_grouping.html.erb
<div class="side-bar-item grouping">
  <h2>Grouping</h2>
  <div class="grouping-list">
    <label class="radio-container">None
      <%= radio_button_tag('grouping', "none", true, class:'input_radio') %>
      <span class="radio-checkmark"></span>
    </label>
    <label class="radio-container">Baseline result
      <%= radio_button_tag('grouping', "baseline_result", false, class:'input_radio') %>
      <span class="radio-checkmark"></span>
    </label>
    <label class="radio-container">Diabetes type
      <%= radio_button_tag('grouping', "diabetes_type", false, class:'input_radio') %>
      <span class="radio-checkmark"></span>
    </label>
    <label class="radio-container">Ethnicity
      <%= radio_button_tag('grouping', "ethnicity", false, class:'input_radio') %>
      <span class="radio-checkmark"></span>
    </label>
    <label class="radio-container">Sex
      <%= radio_button_tag('grouping', "sex", false, class:'input_radio') %>
      <span class="radio-checkmark"></span>
    </label>
    <label class="radio-container">Deprivation decile
      <%= radio_button_tag('grouping', "deprivation", false, class:'input_radio') %>
      <span class="radio-checkmark"></span>
    </label>
    <label class="radio-container">GP CCG
      <%= radio_button_tag('grouping', "ccg", false, class:'input_radio') %>
      <span class="radio-checkmark"></span>
    </label>
  </div>
</div>

app/views/viz_ones/_plot_item_container.html.erb
<div id="plot-item-container" class="plot-item">
</div>

app/views/viz_ones/_sex.html.erb
<h3>Sex</h3>
  <div class="filter-list-2">
  <label class="checkbox-container">Female
    <%= check_box_tag('sex[]', "FEMALE", true, {:multiple => true, :class => 'input_checkbox'}) %>
    <span class="checkbox-checkmark"></span>
  </label>

  <label class="checkbox-container">Male
    <%= check_box_tag('sex[]', "MALE", true, {:multiple => true, :class => 'input_checkbox'}) %>
    <span class="checkbox-checkmark"></span>
  </label>
</div>

app/views/viz_ones/_x_measure.html.erb
<div class="side-bar-item measure">
	<h2>Measure (x-axis)</h2>
	<div class="measure-list">
		<label class="radio-container">Age
		  <%= radio_button_tag('x_measure', "age", true, class:'input_radio') %>
		  <span class="radio-checkmark"></span>
		</label>
		<label class="radio-container">HbA1c
		  <%= radio_button_tag('x_measure', "hba1c", false, class:'input_radio') %>
		  <span class="radio-checkmark"></span>
		</label>
		<label class="radio-container">Cholesterol
		  <%= radio_button_tag('x_measure', "chol", false, class:'input_radio') %>
		  <span class="radio-checkmark"></span>
		</label>
		<label class="radio-container">eGFR
		  <%= radio_button_tag('x_measure', "egfr", false, class:'input_radio') %>
		  <span class="radio-checkmark"></span>
		</label>
		<label class="radio-container">BMI
		  <%= radio_button_tag('x_measure', "bmi", false, class:'input_radio') %>
		  <span class="radio-checkmark"></span>
		</label>
		<label class="radio-container">BP
		  <%= radio_button_tag('x_measure', "bp", false, class:'input_radio') %>
		  <span class="radio-checkmark"></span>
		</label>
	</div>
</div>

app/views/viz_ones/_y_measure.html.erb
<div class="side-bar-item measure">
	<h2>Measure (y-axis)</h2>
	<div class="measure-list">
		<label class="radio-container">HbA1c
		  <%= radio_button_tag('y_measure', "hba1c", true, class:'input_radio') %>
		  <span class="radio-checkmark"></span>
		</label>
		<label class="radio-container">Cholesterol
		  <%= radio_button_tag('y_measure', "chol", false, class:'input_radio') %>
		  <span class="radio-checkmark"></span>
		</label>
		<label class="radio-container">eGFR
		  <%= radio_button_tag('y_measure', "egfr", false, class:'input_radio') %>
		  <span class="radio-checkmark"></span>
		</label>
		<label class="radio-container">BMI
		  <%= radio_button_tag('y_measure', "bmi", false, class:'input_radio') %>
		  <span class="radio-checkmark"></span>
		</label>
		<label class="radio-container">BP
		  <%= radio_button_tag('y_measure', "bp", false, class:'input_radio') %>
		  <span class="radio-checkmark"></span>
		</label>
	</div>
</div>

app/views/viz_ones/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Project KIP</title>
  <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Press+Start+2P|Quicksand" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
  <script src="https://d3js.org/d3.v5.js"></script>
</head>

<body>
<div class="wrapper">
    <header>
      <div>
          <h1>KHP-D Interactive Platform</h1>
        </div>
    </header>

    <div class="main">
      <div class="main-flex">
        <% # Side bar items %>
        
        
        <div class="side-bar">
          <%= form_tag(search_viz_ones_path, :id => 'filter_form') do %>
            <%= render('viz_ones/x_measure') %>
            <%= render('viz_ones/y_measure') %>
            <%= render('viz_ones/grouping') %>
            <%= render('viz_ones/filter') %>
            <%= render('viz_ones/controls') %>
          <% end %>
        </div>
        <% # The right side panel -%>
        <div class="plot">  
          <%= render('viz_ones/plot_item_container') %>
        </div>
      </div>
    </div>
</div>

<script>
  const year_box = document.querySelector('.year-box')
  const left_arrow = document.querySelector('.control-left')
  const right_arrow = document.querySelector('.control-right')

  left_arrow.addEventListener('click', function(){ 
    year_box.value > +2009 ? year_box.value-- : year_box.value = year_box.value
  })

  right_arrow.addEventListener('click', function(){ 
    year_box.value < +2016 ? year_box.value++ : year_box.value = year_box.value
  })
  
</script>